spring.application.name=biblioteca

spring.data.mongodb.uri=mongodb+srv://admin:biblioteca123@cluster0.pxffgib.mongodb.net/biblioteca?retryWrites=true&w=majority


logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

server.port=8081